# Generated by Django 3.1.6 on 2021-02-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210219_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='is_for_sale',
        ),
        migrations.RemoveField(
            model_name='size',
            name='is_for_sale',
        ),
        migrations.AddField(
            model_name='colorsize',
            name='is_for_sale',
            field=models.BooleanField(default=1),
        ),
    ]
