# Generated by Django 3.1.6 on 2021-02-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsize',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colorsize',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
