# Generated by Django 3.1.6 on 2021-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210224_1831'),
        ('product', '0005_auto_20210224_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorSize',
            new_name='ProductOption',
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='product_options',
        ),
    ]
