# Generated by Django 3.1.6 on 2021-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210218_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
