# Generated by Django 3.1.6 on 2021-02-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
            options={
                'db_table': 'admin_levels',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=2000)),
                ('birth', models.DateField(null=True)),
                ('website', models.URLField(null=True)),
                ('about', models.CharField(max_length=100, null=True)),
                ('admin_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.adminlevel')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
