# Generated by Django 3.1.6 on 2021-02-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='brand',
        ),
    ]
