# Generated by Django 3.1.6 on 2021-02-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_adminlevel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.adminlevel'),
        ),
    ]
