# Generated by Django 3.1.6 on 2021-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('orderer_name', models.CharField(max_length=45)),
                ('orderer_phone', models.CharField(max_length=45)),
                ('orderer_email', models.CharField(max_length=2000)),
                ('delivery_name', models.CharField(max_length=45)),
                ('delivery_phone', models.CharField(max_length=45)),
                ('delivery_address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('order_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'ordered_products',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
    ]
