# Generated by Django 3.1.6 on 2021-02-19 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210218_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='in_cart_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 19, 11, 3, 21, 222446, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='purchased_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
