# Generated by Django 3.1.6 on 2021-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210219_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='color_size',
            new_name='product_option',
        ),
    ]
